# Generated by Django 4.2 on 2025-06-25 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_userprofile"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentparticipation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.userprofile"
            ),
        ),
    ]
