# Generated by Django 4.2 on 2025-06-25 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_contentparticipation_user"),
        ("user", "0002_userprofile"),
        ("chat", "0003_alter_chatsession_user_alter_message_sender_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
