# Generated by Django 4.2 on 2025-06-25 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowstep",
            name="workflow",
        ),
        migrations.RenameField(
            model_name="character",
            old_name="description",
            new_name="system_prompt",
        ),
        migrations.DeleteModel(
            name="WorkFlow",
        ),
        migrations.DeleteModel(
            name="WorkFlowStep",
        ),
    ]
